@access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4MjMyNjIyLCJpYXQiOjE3NTgyMzIzMjIsImp0aSI6IjU0ZjdkODBmZmVhYjQ2YzNhMjFlNDNkNDQ5ZDE3NDZkIiwidXNlcl9pZCI6Mn0.q1LvuEMLMdyiG7oB8fs8UWBzBq2QWvGicKlm9YUkXKw
@refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1ODMxODcyMiwiaWF0IjoxNzU4MjMyMzIyLCJqdGkiOiJhOTNiZDUzZGUyN2Q0NzJkODlhZWM0OWYzOTBjODRhNCIsInVzZXJfaWQiOjJ9.dCi_bRqHmv_Xrb4aMg-QdUdocrPG7U7ZgAlw9l7F7gU
@host=http://localhost:8000


### log-in
POST http://localhost:8000/api/login/
Content-Type: application/json

{ "username": "alfarhostel", "password": "djangoalfar" }


### refresh
POST {{host}}/api/refresh/
Content-Type: application/json

{"refresh":"{{refresh}}"}


### get-cliente
GET {{host}}/api/v1/clientes/
Authorization: Bearer {{access}}


### crear cliente
POST {{host}}/api/v1/clientes/
Authorization: Bearer {{access}}
Content-Type: application/json

{
    "nombre": "sheila",
    "apellido": "balmaceda",
    "documento": "44692776",
    "telefono": "2236059934",
    "direccion": "casa",
    "patente": "ABC143"
  }